### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jimlynnjulian** [MrShoenel/mkvinfo2json#1]
Add the inversion; import json tag file into mkv.

**Comment by MrShoenel** [comment]
Hey! You opened and closed this so quickly, I haven't really understood what this was even about 😄 
Would you care to elaborate a bit?

**Comment by jimlynnjulian** [comment]
Apologies. Wrong tool for the task I had in mind (mkvinfo). Have a good one.

**Comment by MrShoenel** [comment]
No worries, thanks for clearing it up :)
