### ISSUE TITLE
Does not deliver all audio tracks

### ISSUE THREAD

**Issue by JPT77** [MrShoenel/mkvinfo2json#2]
Hi, 
thanks for creating this great tool. I am new to json, but I believe it is the best way to interpret complex information like mkvinfo output. (20 years ago I would have used XML queries)

I just tried extracting audio track info from a bunch of files, but it does not work. 

This 

	$ mkvinfo file.mkv 
	+ EBML-Kopf
	|+ EBML-Version: 1
	|+ EBML-Leseversion: 1
	|+ Maximale EBML-ID-Länge: 4
	|+ Maximale Länge des EBML-Längenattributes: 8
	|+ Dokumententyp: matroska
	|+ Dokumententyp, Version: 4
	|+ Dokumententyp, Leseversion: 2
	+ Segment: Größe 303956766
	|+ Seekkopf (Untereinträge werden ausgelassen)
	|+ Segment-Information
	| + Zeitstempelskalierungsfaktor: 1000000
	| + Multiplexeranwendung: libebml v1.3.0 + libmatroska v1.4.1
	| + Schreibende Anwendung: mkvmerge v6.4.1 ('Omega Point') built on Sep 16 2013 22:05:10
	| + Dauer: 00:20:44.928000000
	| + Datum: 2013-10-12 11:34:09 UTC
	| + Segment-UID: 0x99 0x8b 0xab 0x59 0x28 0x8c 0xd3 0x9a 0x97 0x6e 0x2d 0xfc 0x46 0x0d 0x90 0x9c
	| + Titel: 07x06 Der Schmetterlings-Defekt (2012)
	|+ Spuren
	| + Spur
	|  + Spurnummer: 1 (Spur-ID für Mkvmerge & Mkvextract: 0)
	|  + Spur-UID: 2561628302
	|  + Spurtyp: Video
	|  + »Anzeige erzwingen«-Schalter: 1
	|  + Framebündelungs-Schalter: 0
	|  + Minimaler Zwischenspeicher: 1
	|  + Codec-ID: V_MPEG4/ISO/AVC
	|  + Private Codec-Daten: Größe 55 (H.264-Profil: High @L4.1)
	|  + Standarddauer: 00:00:00.040000000 (25.000 Bilder/Felder pro Sekunde im Falle einer Videospur)
	|  + Sprache: eng
	|  + Videospur
	|   + Breite in Pixeln: 720
	|   + Höhe in Pixeln: 404
	|   + Anzeigebreite: 720
	|   + Anzeigehöhe: 404
	| + Spur
	|  + Spurnummer: 2 (Spur-ID für Mkvmerge & Mkvextract: 1)
	|  + Spur-UID: 7779615915173145498
	|  + Spurtyp: Audio
	|  + Codec-ID: A_AC3
	|  + Standarddauer: 00:00:00.032000000 (31.250 Bilder/Felder pro Sekunde im Falle einer Videospur)
	|  + Sprache: ger
	|  + Audiospur
	|   + Abtastrate: 48000
	|   + Kanäle: 6
	|  + »Standardspur«-Schalter: 1
	|  + Name: Deutsch
	| + Spur
	|  + Spurnummer: 3 (Spur-ID für Mkvmerge & Mkvextract: 2)
	|  + Spur-UID: 2979035302
	|  + Spurtyp: Audio
	|  + »Standardspur«-Schalter: 0
	|  + Codec-ID: A_AC3
	|  + Standarddauer: 00:00:00.032000000 (31.250 Bilder/Felder pro Sekunde im Falle einer Videospur)
	|  + Audiospur
	|   + Abtastrate: 48000
	|   + Kanäle: 6
	|  + »Anzeige erzwingen«-Schalter: 0
	|  + »Originalsprache«-Schalter: 1
	|  + Name: Englisch
	|+ EBML-Platzhalter: Größe 5100
	|+ Cluster

results in 

    {
      "filePath": "file.mkv",
      "dirName": "/path/",
      "fileSize": 303956830,
      "head": {
        "EBML-Version": 1,
        "EBML-Leseversion": 1,
        "Maximale EBML-ID-Länge": 4,
        "Maximale Länge des EBML-Längenattributes": 8,
        "Dokumententyp": "matroska",
        "Dokumententyp, Version": 4,
        "Dokumententyp, Leseversion": 2
      },
      "segInfo": {
        "Seekkopf (Untereinträge werden ausgelassen)": null,
        "Segment-Information": null,
        "Zeitstempelskalierungsfaktor": 1000000,
        "Multiplexeranwendung": "libebml v1.3.0 + libmatroska v1.4.1",
        "Schreibende Anwendung": "mkvmerge v6.4.1 ('Omega Point') built on Sep 16 2013 22:05:10",
        "Dauer": "00:20:44.928000000",
        "Datum": "2013-10-12 11:34:09 UTC",
        "Segment-UID": "0x99 0x8b 0xab 0x59 0x28 0x8c 0xd3 0x9a 0x97 0x6e 0x2d 0xfc 0x46 0x0d 0x90 0x9c",
        "Titel": "title",
        "Spuren": null,
        "Spur": null,
        "Spurnummer": "3 (Spur-ID für Mkvmerge & Mkvextract: 2)",
        "Spur-UID": 2979035302,
        "Spurtyp": "Audio",
        "»Anzeige erzwingen«-Schalter": 0,
        "Framebündelungs-Schalter": 0,
        "Minimaler Zwischenspeicher": 1,
        "Codec-ID": "A_AC3",
        "Private Codec-Daten": "Größe 55 (H.264-Profil: High @L4.1)",
        "Standarddauer": "00:00:00.032000000 (31.250 Bilder/Felder pro Sekunde im Falle einer Videospur)",
        "Sprache": "ger",
        "Videospur": null,
        "Breite in Pixeln": 720,
        "Höhe in Pixeln": 404,
        "Anzeigebreite": 720,
        "Anzeigehöhe": 404,
        "Audiospur": null,
        "Abtastrate": 48000,
        "Kanäle": 6,
        "»Standardspur«-Schalter": 0,
        "Name": "Englisch",
        "»Originalsprache«-Schalter": 1,
        "EBML-Platzhalter": "Größe 5100",
        "Cluster": null
      },
      "segTracks": [],
      "chapters": []
    },

might it be because my system is set to German? 
setting LANG and LANGUAGE to EN did not change the mkvinfo language.

**Comment by JPT77** [comment]
Using LC_ALL I was able to get english language. but it does not help either. 
Seems the handling of spaces before the + does not work well. :(

    {
      "filePath": "file.mkv",
      "dirName": "/path/",
      "fileSize": 180055728,
      "head": {
        "EBML version": 1,
        "EBML read version": 1,
        "Maximum EBML ID length": 4,
        "Maximum EBML size length": 8,
        "Document type": "matroska",
        "Document type version": 2,
        "Document type read version": 2
      },
      "segInfo": {
        "Seek head (subentries will be skipped)": null,
        "Segment information": null,
        "Timestamp scale": 1000000,
        "Multiplexing application": "libebml v1.2.3 + libmatroska v1.3.0",
        "Writing application": "mkvmerge v5.1.0 ('And so it goes') built on Nov 28 2011 23:58:28",
        "Duration": "00:20:45.568000000",
        "Date": "2014-12-20 13:36:04 UTC",
        "Segment UID": "0x80 0x3f 0x24 0xa0 0xc4 0x3a 0x5b 0xb8 0xa2 0x90 0x9e 0xa6 0x56 0xb5 0xf4 0x39",
        "Title": "title",
        "Tracks": null,
        "Track": null,
        "Track number": "2 (track ID for mkvmerge & mkvextract: 1)",
        "Track UID": 2994857630,
        "Track type": "audio",
        "\"Lacing\" flag": 0,
        "Minimum cache": 1,
        "Codec ID": "A_AC3",
        "Codec's private data": "size 46 (H.264 profile: High @L3.1)",
        "Default duration": "00:00:00.032000000 (31.250 frames/fields per second for a video track)",
        "Language": "ger",
        "Video track": null,
        "Pixel width": 720,
        "Pixel height": 404,
        "Display width": 720,
        "Display height": 404,
        "Audio track": null,
        "Sampling frequency": 48000,
        "Channels": 6,
        "Name": "Deutsch",
        "EBML void": "size 5091",
        "Cluster": null
      },
      "segTracks": [],
      "chapters": []
    }

**Comment by JPT77** [comment]
mh. already integrated into mkv tools?

`mkvmerge --identification-format json --identify yourfile.mkv`

**Comment by MrShoenel** [comment]
Thanks for your bug report :) I haven't looked at the code in a while. Are you able to pin down the exact problem? If so, you could create a pull request and I'd be happy to merge it :)
As you see, `mkvmerge` can be used to produce JSON output these days; `mkvinfo2json` was created before that time.

However, back then, I had focused on a similar project: https://github.com/MrShoenel/ff-fingerprinter
This one is still maintained and additionally to extracting meta information, also hashes the streams in files.
Also, it works with anything that `ffmpeg` can read, so you might give that a try?

**Comment by JPT77** [comment]
Well, I had a look into the program code and realized it was language specific. 
In my opinion it should just parse the formatting letters and not interpret the content itself. 

But as noted in my last message, the project is obsolete as JSON is already included in mkvmerge. 
You only need to run `mkvmerge -J file` to get json output similar to what your code delivers.

So, thank you very much for this project and your willingness to fix it, but it seems it's not necessary any more.

**Comment by MrShoenel** [comment]
Are you using the included web application? Because it kind of requires the format that is produced by this application.
I haven't used it in a while, but I think that once I will, I am going to fix the error :)
I will close this for the moment, thanks for your feedback!

**Comment by JPT77** [comment]
I don't know about any web app 8)

**Comment by MrShoenel** [comment]
This tool was actually made to view the JSON and all of its analyzed files in a web app with good filtering capabilities. For example, show all movies with at least two subtitle tracks and at least one audio track that is German (for example). Or filter all movies by resolution etc.
